apiVersion: v1
kind: ServiceAccount
metadata:
  # SA bound to the VSO namespace for transit engine auth
  namespace: vault-secrets-operator-system
  name: demo-operator
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: argocd
spec:
  method: kubernetes
  mount: openshift-auth-mount
  namespace: ecosystem
  kubernetes:
    role: digibank
    serviceAccount: default
    audiences:
      - vault